import { jsx as _jsx } from "react/jsx-runtime";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from "@react-three/drei";
export function Maquina(props) {
    const { nodes, materials } = useGLTF("/maquina3.glb");
    return (_jsx("group", Object.assign({}, props, { dispose: null, children: _jsx("mesh", { castShadow: true, receiveShadow: true, geometry: nodes.BrazoLaptop_low.geometry, material: materials.TextureMaq, position: [1.186, 1.449, -1.226], scale: 0.025 }) })));
}
useGLTF.preload("/maquina3.glb");
