/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { Mesh, Material } from "three";

interface GLTFNodes {
  BrazoLaptop_low: Mesh;
}

interface GLTFMaterials {
  TextureMaq: Material;
}

type GLTFResult = {
  nodes: GLTFNodes;
  materials: GLTFMaterials;
};

export function Maquina(props: any) {
  const { nodes, materials } = useGLTF(
    "/maquina3.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BrazoLaptop_low.geometry}
        material={materials.TextureMaq}
        position={[1.186, 1.449, -1.226]}
        scale={0.025}
      />
    </group>
  );
}

useGLTF.preload("/maquina3.glb");
